name: "Bug Fix Pull Request"
description: "Template for fixing bugs"
title: "Fix: [Bug Description]"
labels: ["bug", "fix"]
body:
  - type: textarea
    id: issue
    attributes:
      label: Related Issue
      description: Link the issue this PR fixes.
      placeholder: Fixes #123
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Describe how the bug was reproduced before.
      placeholder: 1. …\n2. …\n3. …

  - type: textarea
    id: fix
    attributes:
      label: Fix Description
      description: Explain what was changed to fix the issue.
      placeholder: What is the root cause and the applied fix?
    validations:
      required: true

  - type: textarea
    id: regression
    attributes:
      label: Regression Risk
      description: Could this break other functionality?
      placeholder: Any modules at risk?