name: "Docs Pull Request"
description: "Template for documentation changes"
title: "Docs: [Title]"
labels: ["documentation"]
body:
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What documentation areas were updated?
      placeholder: README, handbook, wiki, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Proofread and spell-checked
        - label: Screenshots/examples added where needed
        - label: Linked related code changes (if any)