name: "EPIC 🗺️"
description: "Use this to define a high-level initiative with linked child issues"
title: "[EPIC] <short name>"
labels: ["epic"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Fill out this EPIC to define scope, success, and child issues. Use the checklist section to link issues (e.g., `- [ ] #123`).

  - type: input
    id: epic_summary
    attributes:
      label: "Epic Summary"
      description: "One sentence describing the outcome of this EPIC"
      placeholder: "Ex: Automate issue assignment across the repository"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "Problem / Context"
      description: "Why this matters; what pain it resolves"
      placeholder: "Current workflow requires manual assignment; issues slip through unowned."
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: "Scope"
      description: "What is in scope for this EPIC"
      placeholder: "- Add CODEOWNERS for ownership\n- Add GitHub Action for label-based assigning\n- Configure Project Workflows automation"
    validations:
      required: true

  - type: textarea
    id: out_of_scope
    attributes:
      label: "Out of Scope"
      description: "What is explicitly not covered"
      placeholder: "Ex: Team-wide SLA policy; cross-repo automation"
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance Criteria"
      description: "Clear conditions for 'done'"
      placeholder: "- New issues are auto-assigned via at least one mechanism\n- Documentation exists for maintainers\n- Demo verified in this repo"
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: "Child Issues (Task List)"
      description: "Link issues with task list items (use #issueNumber)."
      placeholder: "- [ ] #123 CODEOWNERS\n- [ ] #124 GitHub Action\n- [ ] #125 Project Workflows"
    validations:
      required: false

  - type: textarea
    id: timeline
    attributes:
      label: "Timeline / Milestones"
      description: "Rough dates or phases"
      placeholder: "- Week 1: Draft & Review\n- Week 2: Implement\n- Week 3: Verify & Document"
    validations:
      required: false

  - type: textarea
    id: stakeholders
    attributes:
      label: "Stakeholders / Owners"
      description: "People responsible or impacted"
      placeholder: "- Owner: @your-handle\n- Review: @docs-lead"
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: "Risks & Mitigations"
      description: "Potential blockers & how to handle them"
      placeholder: "- Action permissions missing → Add workflow permissions"
    validations:
      required: false

  - type: textarea
    id: metrics
    attributes:
      label: "Success Metrics"
      description: "How we know this worked"
      placeholder: "- 100% of new issues assigned within 1 minute"
    validations:
      required: false
