name: Assign Iteration from Sprint Label

on:
  issues:
    types: [opened, labeled, reopened]
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  set-iteration:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Sprint label
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            // Find a label like "Sprint 2"
            const labels = (context.payload.issue?.labels || []).map(l => (typeof l === 'string' ? l : l.name) || '');
            const match = labels.map(s => s.match(/^sprint\s*(\d+)$/i)).find(Boolean);
            if (!match) {
              core.info('No Sprint N label found; skipping.');
              core.setOutput('sprint', '');
              return;
            }
            core.setOutput('sprint', `Sprint ${match[1]}`);

      - name: Stop if no Sprint label
        if: steps.parse.outputs.sprint == ''
        run: echo "No matching Sprint label; nothing to do."

      - name: Assign Iteration on Project
        if: success() && steps.parse.outputs.sprint != ''
        uses: actions/github-script@v7
        env:
          PROJECT_NUMBER: ${{ vars.PROJECT_NUMBER }}
          SPRINT_FIELD_NAME: ${{ vars.SPRINT_FIELD_NAME }}
        with:
          github-token: ${{ secrets.ORG_GRAPHQL_TOKEN }}
          script: |
            const sprintLabel = `${{ steps.parse.outputs.sprint }}`; // e.g. "Sprint 1"
            const projectNumberRaw = process.env.PROJECT_NUMBER;
            if (!projectNumberRaw) {
              core.setFailed('Missing repo variable PROJECT_NUMBER (set it under Settings → Secrets and variables → Variables).');
              return;
            }
            const projectNumber = parseInt(projectNumberRaw, 10);
            const iterationFieldName = (process.env.SPRINT_FIELD_NAME || 'Sprints').trim();

            const { owner, repo } = context.repo;
            const issueNumber = context.payload.issue.number;

            // Helper: try to fetch project as ORG
            async function getOrgProject(owner, number) {
              const q = `
              query($owner:String!, $number:Int!) {
                  organization(login:$owner) {
                  projectV2(number:$number) {
                    id
                    fields(first:50) {
                      nodes {
                          __typename
                        ... on ProjectV2FieldCommon { id name }
                        ... on ProjectV2IterationField {
                          id
                          name
                          configuration { iterations { id title } }
                        }
                      }
                    }
                  }
                }
                }`;
              try {
                const d = await github.graphql(q, { owner, number });
                return d.organization?.projectV2 || null;
              } catch (e) {
                // swallow org lookup errors; we'll try user next
                core.debug(`Org project lookup failed: ${e.message}`);
                return null;
              }
            }

            // Helper: try to fetch project as USER
            async function getUserProject(owner, number) {
              const q = `
                query($owner:String!, $number:Int!) {
                  user(login:$owner) {
                  projectV2(number:$number) {
                    id
                    fields(first:50) {
                      nodes {
                          __typename
                        ... on ProjectV2FieldCommon { id name }
                        ... on ProjectV2IterationField {
                          id
                          name
                          configuration { iterations { id title } }
                        }
                      }
                    }
                  }
                }
              }`;
              try {
                const d = await github.graphql(q, { owner, number });
                return d.user?.projectV2 || null;
              } catch (e) {
                core.debug(`User project lookup failed: ${e.message}`);
                return null;
              }
            }

            // 1) Resolve project (org first, then user)
            let project = await getOrgProject(owner, projectNumber);
            if (!project) project = await getUserProject(owner, projectNumber);
            if (!project?.id) {
              core.setFailed(`Project number ${projectNumber} not found under "${owner}". Check PROJECT_NUMBER and token scopes/SSO.`);
              return;
            }

            // 2) Find the Iteration field
            const fields = project.fields?.nodes || [];
            const iterField = fields.find(f => f.__typename === 'ProjectV2IterationField' && f.name === iterationFieldName);
            if (!iterField) {
              const names = fields.map(f => `${f.__typename}:${f.name}`).join(', ');
              core.setFailed(`Iteration field "${iterationFieldName}" not found. Fields: ${names || '(none)'}`);
              return;
            }

            // 3) Match the iteration by title, e.g., "Sprint 1"
            const iterations = iterField.configuration?.iterations || [];
            const targetIter = iterations.find(it => (it.title || '').trim().toLowerCase() === sprintLabel.toLowerCase());
            if (!targetIter) {
              const titles = iterations.map(i => i.title).join(', ') || '(none)';
              core.setFailed(`Iteration "${sprintLabel}" not found in field "${iterationFieldName}". Available: ${titles}`);
              return;
            }

            // 4) Get Issue node id + existing project item
            const qIssue = `
              query($owner:String!, $repo:String!, $number:Int!) {
                repository(owner:$owner, name:$repo) {
                  issue(number:$number) {
                    id
                    projectItems(first:50) { nodes { id project { id } } }
                  }
                }
              }`;
            const dIssue = await github.graphql(qIssue, { owner, repo, number: issueNumber });
            const issue = dIssue.repository?.issue;
            if (!issue?.id) {
              core.setFailed(`Issue #${issueNumber} not found.`);
              return;
            }
            let itemId = issue.projectItems?.nodes?.find(n => n.project?.id === project.id)?.id || null;

            // 5) Add to project if missing
            if (!itemId) {
              const mutAdd = `
                mutation($projectId:ID!, $contentId:ID!) {
                  addProjectV2ItemById(input:{projectId:$projectId, contentId:$contentId}) {
                    item { id }
                  }
                }`;
              const added = await github.graphql(mutAdd, { projectId: project.id, contentId: issue.id });
              itemId = added.addProjectV2ItemById?.item?.id;
              if (!itemId) {
                core.setFailed('Failed to add issue to project.');
                return;
              }
            }

            // 6) Set Iteration field value
            const mutUpdate = `
              mutation($projectId:ID!, $itemId:ID!, $fieldId:ID!, $iterId:String!) {
                updateProjectV2ItemFieldValue(input:{
                  projectId:$projectId,
                  itemId:$itemId,
                  fieldId:$fieldId,
                  value:{ iterationId:$iterId }
                }) {
                  projectV2Item { id }
                }
              }`;
            await github.graphql(mutUpdate, {
              projectId: project.id,
              itemId,
              fieldId: iterField.id,
              iterId: targetIter.id
            });

            core.info(`✅ Set Iteration "${sprintLabel}" on Issue #${issueNumber} (${owner}/${repo}) in Project #${projectNumber}.`);