name: Milestone → Wiki (foldered Sprints + Sidebar + All page + Dynamic Home)

on:
  milestone:
    types: [closed, opened, edited]
  workflow_dispatch:
    inputs:
      milestone_number:
        description: "Milestone number to export (optional)"
        required: false

permissions:
  contents: write

env:
  MAX_LATEST: "3"   # set "2" to keep only two latest closed sprints in the sidebar

jobs:
  export-sprint-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (to get script)
        uses: actions/checkout@v4

      - name: Checkout Wiki repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies (Octokit, etc.)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Build sprint pages (external script)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIKI_DIR: wiki
          MAX_LATEST: ${{ env.MAX_LATEST }}
          MILESTONE_NUMBER: ${{ inputs.milestone_number }}
        run: node .github/scripts/milestone-to-wiki-folders.js

      - name: Commit & Push wiki changes
        run: |
          cd wiki
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "docs(wiki): update sprint pages, sidebar, All, and dynamic Home (folders)" || echo "No changes to commit."
          git push