name: Render README Variables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Render README placeholders
        run: |
          node --version
          node scripts/render-readme.js

      - name: Commit README if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): render repo placeholders"
          file_pattern: README.md