name: Set issue Type from labels

on:
  issues:
    types: [opened, labeled, reopened]

permissions:
  issues: write

jobs:
  set-type:
    runs-on: ubuntu-latest
    steps:
      - name: Map label -> type name
        id: map
        run: |
          labels_json='${{ toJson(github.event.issue.labels.*.name) }}'
          TYPE_NAME=""
          if echo "$labels_json" | grep -qi '"bug"';          then TYPE_NAME="Bug";          fi
          if echo "$labels_json" | grep -qi '"enhancement"';  then TYPE_NAME="Enhancement";  fi
          if echo "$labels_json" | grep -qi '"documentation"';then TYPE_NAME="Documentation";fi
          if echo "$labels_json" | grep -qi '"duplicate"';    then TYPE_NAME="Duplicate";    fi
          if echo "$labels_json" | grep -qi '"epic"';          then TYPE_NAME="Epic";         fi
          echo "TYPE_NAME=$TYPE_NAME" >> $GITHUB_OUTPUT
          echo "Mapped TYPE_NAME=$TYPE_NAME"

      - name: Skip if no mapped type
        if: steps.map.outputs.TYPE_NAME == ''
        run: echo "No matching label for Issue Type. Skipping."

      - name: Look up Issue Type ID (GraphQL)
        if: steps.map.outputs.TYPE_NAME != ''
        id: lookup
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const typeName = `${{ toJSON(steps.map.outputs.TYPE_NAME) }}`.replace(/^"|"$/g,'');
            const owner = context.repo.owner;
            const repo  = context.repo.repo;

            const q = `
              query($owner:String!, $repo:String!) {
                repository(owner:$owner, name:$repo) {
                  id
                  owner {
                    __typename
                    ... on Organization {
                      id
                      login
                      issueTypes(first:50) {
                        nodes { id, name }
                      }
                    }
                  }
                }
              }`;
            const data = await github.graphql(q, { owner, repo });
            const org = data.repository.owner;

            if (!org || !org.issueTypes) {
              core.setFailed("Issue Types are not enabled for this organization.");
              return;
            }

            const match = org.issueTypes.nodes.find(
              t => t.name.toLowerCase() === typeName.toLowerCase()
            );
            if (!match) {
              core.setFailed(`No Issue Type named "${typeName}" found. Create it in org settings, or adjust your mapping.`);
              return;
            }

            core.notice(`Resolved Issue Type "${typeName}" -> ${match.id}`);
            // Return the ID as the step's output (because result-encoding: string)
            return match.id;
      # ^ The value returned becomes steps.lookup.outputs.result

      - name: Set Issue Type (GraphQL)
        if: steps.map.outputs.TYPE_NAME != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner  = context.repo.owner;
            const repo   = context.repo.repo;
            const number = ${{ github.event.issue.number }};
            const issueTypeId = `${{ toJSON(steps.lookup.outputs.result) }}`.replace(/^"|"$/g,'');

            // 1) Fetch the issue node ID
            const q1 = `
              query($owner:String!, $repo:String!, $number:Int!) {
                repository(owner:$owner, name:$repo) {
                  issue(number:$number) { id }
                }
              }`;
            const d1 = await github.graphql(q1, { owner, repo, number });
            const issueId = d1.repository.issue.id;

            // 2) Update the issue type
            const mut = `
              mutation($issueId:ID!, $issueTypeId:ID!) {
                updateIssue(input: {id:$issueId, issueTypeId:$issueTypeId}) {
                  issue { id number }
                }
              }`;
            await github.graphql(mut, { issueId, issueTypeId });
            core.notice(`Issue #${number}: type updated to ${ ${{
              toJSON(steps.map.outputs.TYPE_NAME)
            }} }.`);
