name: Update Sprint Badge

on:
  schedule:
    - cron: '0 6 * * *'   # daily at 06:00 UTC
  workflow_dispatch:
  issues:
    types: [opened, edited, closed, deleted, reopened]
  milestone:
    types: [created, edited, closed, opened]

permissions:
  contents: write
  issues: read

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine sprint from milestones
        id: sprint
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Get all milestones (open first, then recently closed as fallback)
            const open = await github.rest.issues.listMilestones({
              owner, repo, state: 'open', sort: 'due_on', direction: 'asc'
            });

            let chosen = open.data[0];
            let status = 'Planned';
            let color = 'lightgrey';

            if (!chosen) {
              const closed = await github.rest.issues.listMilestones({
                owner, repo, state: 'closed', sort: 'due_on', direction: 'desc'
              });
              chosen = closed.data[0] || null;
              if (chosen) { status = 'Completed'; color = 'success'; }
            } else {
              // Infer status for open milestone
              const today = new Date().toISOString().slice(0,10);
              const due = chosen.due_on ? chosen.due_on.slice(0,10) : null;

              // Use issue stats to infer progress
              const mstats = await github.rest.issues.listForRepo({
                owner, repo, milestone: chosen.number, state: 'all', per_page: 1
              });
              // GitHub API doesn't return closed count here efficiently without pagination,
              // so rely on milestone fields:
              const closedCount = chosen.closed_issues || 0;
              const openCount = chosen.open_issues || 0;

              if (due && due < today) { status = 'Overdue'; color = 'red'; }
              else if (closedCount > 0) { status = 'In Progress'; color = 'blue'; }
              else { status = 'Planned'; color = 'lightgrey'; }
            }

            // Extract sprint number from title if possible
            let sprintNum = '';
            if (chosen && chosen.title) {
              const m = chosen.title.match(/Sprint\s+(\d+)/i);
              sprintNum = m ? m[1] : chosen.title;
            } else {
              sprintNum = 'N/A';
            }

            // Build shields.io label (spaces -> hyphens, status with double dashes between words)
            function hyphenate(s){ return String(s).trim().replace(/\s+/g, '-'); }
            const statusLabel = String(status).replace(/\s+/g, '--');
            const label = `Sprint-${hyphenate(sprintNum)}--${statusLabel}`;

            core.setOutput('badge', `![Sprint](https://img.shields.io/badge/${encodeURIComponent(label)}-${color})`);
            core.setOutput('title', chosen ? chosen.title : 'No Active Sprint');
            core.setOutput('status', status);

      - name: Update README badge between markers
        run: |
          FILE="README.md"
          if [ ! -f "$FILE" ]; then
            echo "README.md not found in repo root. Ensure file exists."
            exit 1
          fi
          BADGE='${{ steps.sprint.outputs.badge }}'
          # Replace content between markers
          awk -v badge="$BADGE" '
            BEGIN{inblock=0}
            /<!-- SPRINT BADGE START -->/ {print; print badge; inblock=1; next}
            /<!-- SPRINT BADGE END -->/ {print; inblock=0; next}
            inblock==0 {print}
          ' "$FILE" > README.md.tmp && mv README.md.tmp "$FILE"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): update Sprint badge from milestone"
          file_pattern: README.md