name: Update Sprint Badge

on:
  schedule:
    - cron: '0 6 * * *'   # daily at 06:00 UTC
  workflow_dispatch:
  issues:
    types: [opened, edited, closed, deleted, reopened]
  milestone:
    types: [created, edited, closed, opened]

permissions:
  contents: write
  issues: read

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine sprint from milestones
        id: sprint
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Get milestones (open first)
            const open = await github.rest.issues.listMilestones({
              owner, repo, state: 'open', sort: 'due_on', direction: 'asc'
            });

            let chosen = open.data[0];
            let status = 'Planned';
            let color = 'lightgrey';

            if (!chosen) {
              const closed = await github.rest.issues.listMilestones({
                owner, repo, state: 'closed', sort: 'due_on', direction: 'desc'
              });
              chosen = closed.data[0] || null;
              if (chosen) { status = 'Completed'; color = 'success'; }
            } else {
              const today = new Date().toISOString().slice(0,10);
              const due = chosen.due_on ? chosen.due_on.slice(0,10) : null;

              const closedCount = chosen.closed_issues || 0;
              if (due && due < today) { status = 'Overdue'; color = 'red'; }
              else if (closedCount > 0) { status = 'In Progress'; color = 'blue'; }
              else { status = 'Planned'; color = 'lightgrey'; }
            }

            function hyphenate(s){ return String(s || '').trim().replace(/\s+/g, '-'); }
            const m = chosen && chosen.title ? chosen.title.match(/Sprint\s+(\d+)/i) : null;
            const sprintNum = m ? m[1] : (chosen ? chosen.title : 'N-A');
            const statusLabel = String(status).replace(/\s+/g, '--');
            const label = `Sprint-${hyphenate(sprintNum)}--${statusLabel}`;

            core.setOutput('badge', `![Sprint](https://img.shields.io/badge/${encodeURIComponent(label)}-${color})`);

      - name: Update README badge between inline markers
        shell: bash
        run: |
          FILE="README.md"
          if [ ! -f "$FILE" ]; then
            echo "README.md not found in repo root. Ensure file exists."
            exit 1
          fi
          BADGE='${{ steps.sprint.outputs.badge }}'
          # Replace any content between the inline markers with the new badge, preserving single-line layout
          perl -0777 -pe "s/<!-- SPRINT BADGE START -->.*?<!-- SPRINT BADGE END -->/<!-- SPRINT BADGE START -->${BADGE}<!-- SPRINT BADGE END -->/s" "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): update inline Sprint badge from milestone"
          file_pattern: README.md
